### ISSUE TITLE
issue on restoring

### ISSUE THREAD

**Issue by killmasta93** [junedkhatri31/docker-volume-snapshot#1]
Hi 
Currently using your script which i need to migrate from a docker container to another host but cant seem to get it working
Migrating openproject 
This is what i did, 
on my production server ran 

`docker-volume-snapshot create /projects open.tar`

then copied the tar file to my docker host server and ran

`docker-volume-snapshot restore open.tar /projects `

and copied the files to the same location 

then i ran the docker compose file of openproject which is the same docker compose from the production so the volume location are the same

but when it shows login shows as if its the first time

Thank  you

**Comment by junedkhatri31** [comment]
Hi @killmasta93, In create command you have to specify docker volume name. Not the path to any directory. Have you mounted any docker volume to your container?

**Comment by killmasta93** [comment]
Thanks for the reply, im a bit lost
This is my docker compose 

the information is saved in /projects

```
version: "3.7"

networks:
  frontend:
  backend:

volumes:
  pgdata:
  opdata:

x-op-restart-policy: &restart_policy
  restart: unless-stopped
x-op-image: &image
  image: openproject/community:${TAG:-12}
x-op-app: &app
  <<: [*image, *restart_policy]
  environment:
    RAILS_CACHE_STORE: "memcache"
    OPENPROJECT_CACHE__MEMCACHE__SERVER: "cache:11211"
    OPENPROJECT_RAILS__RELATIVE__URL__ROOT: "${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}"
    DATABASE_URL: "${DATABASE_URL:-postgres://postgres:p4ssw0rd@db/openproject?pool=20&encoding=unicode&reconnect=true}"
    RAILS_MIN_THREADS: 4
    RAILS_MAX_THREADS: 16
    # set to true to enable the email receiving feature. See ./docker/cron for more options
    IMAP_ENABLED: "${IMAP_ENABLED:-false}"
  volumes:
    - /projects/${OPDATA:-opdata}:/var/openproject/assets"

services:
  db:
    image: postgres:13
    <<: *restart_policy
    stop_grace_period: "3s"
    volumes:
      - /projects/${PGDATA:-pgdata}:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-p4ssw0rd}
      POSTGRES_DB: openproject
    networks:
      - backend

  cache:
    image: memcached
    <<: *restart_policy
    networks:
      - backend

  proxy:
    <<: [*image, *restart_policy]
    command: "./docker/prod/proxy"
    ports:
      - "${PORT:-8085}:80"
    environment:
      APP_HOST: web
      OPENPROJECT_RAILS__RELATIVE__URL__ROOT: "${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}"
    depends_on:
      - web
    networks:
      - frontend

  web:
    <<: *app
    command: "./docker/prod/web"
    networks:
      - frontend
      - backend
    depends_on:
      - db
      - cache
      - seeder
    labels:
      - autoheal=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080${OPENPROJECT_RAILS__RELATIVE__URL__ROOT:-}/health_checks/default"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  autoheal:
    image: willfarrell/autoheal:1.2.0
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      AUTOHEAL_CONTAINER_LABEL: autoheal

  worker:
    <<: *app
    command: "./docker/prod/worker"
    networks:
      - backend
    depends_on:
      - db
      - cache
      - seeder

  cron:
    <<: *app
    command: "./docker/prod/cron"
    networks:
      - backend
    depends_on:
      - db
      - cache
      - seeder

  seeder:
    <<: *app
    command: "./docker/prod/seeder"
    restart: on-failure
    networks:
      - backend
```
but the docker mount point 

```
root@dockers:/projects/openproject/compose# docker volume inspect compose_pgdata
[
    {
        "CreatedAt": "2022-07-04T11:01:31-05:00",
        "Driver": "local",
        "Labels": {
            "com.docker.compose.project": "compose",
            "com.docker.compose.version": "1.29.2",
            "com.docker.compose.volume": "pgdata"
        },
        "Mountpoint": "/var/lib/docker/volumes/compose_pgdata/_data",
        "Name": "compose_pgdata",
        "Options": null,
        "Scope": "local"
    }

```

```
root@dockers:/projects/openproject/compose# docker volume inspect compose_opdata
[
    {
        "CreatedAt": "2022-07-04T11:01:31-05:00",
        "Driver": "local",
        "Labels": {
            "com.docker.compose.project": "compose",
            "com.docker.compose.version": "1.29.2",
            "com.docker.compose.volume": "opdata"
        },
        "Mountpoint": "/var/lib/docker/volumes/compose_opdata/_data",
        "Name": "compose_opdata",
        "Options": null,
        "Scope": "local"
    }
]

```
Thank you
